spring:
  cloud:
    bus:
      enabled: false
    config:
      override-none: false
      override-system-properties: false
      allow-override: true
  aop:
    proxy-target-class: true
    auto: true
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  thymeleaf:
    mode: HTML
    cache: true
    encoding: UTF-8
    template-resolver-order: 100
server:
  connection-timeout: 20000
  context-path: /cas
  tomcat:
    basedir: build/tomcat
    remote-ip-header: X-FORWARDED-FOR
    min-spare-threads: 10   #差这个
    uri-encoding: UTF-8
    protocol-header: X-Forwarded-Proto
    protocol-header-https-value: https
    port-header: X-Forwarded-Port
    max-threads: 200
    max-http-post-size: 2097152
    accesslog:
      pattern: '%t %a "%r" %s (%D ms)'
      suffix: .log
      enabled: true
  port: 8080
  max-http-header-size: 2097152
  session:
    tracking-modes: COOKIE
    cookie:
      http-only: true
    timeout: 300
  context-parameters:
    isLog4jAutoInitializationDisabled: true
  compression:
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain
    enabled: true
  error:
    include-stacktrace: ALWAYS
  use-forward-headers: true

# Disble http ssl
warn:
  cookie:
    secure: false

endpoints:
  restart:
    enabled: false
  sensitive: true
  shutdown:
    enabled: false
  enabled: false

# cas
cas:
  theme:
    defaultThemeName: abouerp
  logout:
    followServiceRedirects: true
    removeDescendantTickets: true
  httpWebRequest:
    header:
      xframe: false
  tgc:
    secure: false
  ticket:
    registry:
      redis:
        database: 0
        port: 6379
        usePool: true
        host: localhost
        useSsl: false
  serviceRegistry:
    #自动扫描服务配置，默认开启
    watcherEnabled: true
    #是否从json加载服务
    initFromJson: false
    jpa:
      autocommit: true
      batchSize: 1
      ddlAuto: update
      dialect: org.hibernate.dialect.MySQL5Dialect    #只有这个才会自动生成表
      driverClass: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/portalCas?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC&characterEncoding=utf8
      user: root
      password: chenjinjie
      failFastTimeout: 1
      isolateInternalQueries: false
      leakThreshold: 10
  authn:
    attributeRepository:
      defaultAttributesToRelease: mobile
      jdbc:
        - attributes:
            mobile: mobile
          url: jdbc:mysql://localhost:3306/portalCas?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC&characterEncoding=utf8
          user: root
          password: chenjinjie
          dialect: org.hibernate.dialect.MySQL5Dialect
          driverClass: com.mysql.cj.jdbc.Driver
          sql: select * from Teacher where username = ?
          username: username
    jdbc:
      query:
        - dialect: org.hibernate.dialect.MySQL5Dialect
          driverClass: com.mysql.cj.jdbc.Driver
          fieldDisabled: disable
          fieldExpired: accountExpired
          fieldPassword: password
          sql: select * from Teacher where username = ?
          url: jdbc:mysql://localhost:3306/portalCas?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC&characterEncoding=utf8
          user: root
          password: chenjinjie
          passwordEncoder:
            type: cn.edu.abouerp.cas.PortalPasswordEncoder
            characterEncoding: UTF-8
            encodingAlgorithm: MD5

management:
  security:
    sessions: if_required
    roles: ACTUATOR,ADMIN
    enabled: true
  context-path: /status
  health:
    status:
      order: WARN, DOWN, OUT_OF_SERVICE, UNKNOWN, UP
  add-application-context-header: false
